CREATE TABLE Proveedor (
	id TINYINT IDENTITY (1,1) NOT NULL
	, Nombre VARCHAR (50) NOT NULL
	, Tlf VARCHAR (9) NOT NULL
	, Email VARCHAR (30) NOT NULL
	, CONSTRAINT PK_Proveedor_ProveedorID PRIMARY KEY CLUSTERED (id)
);

